### ISSUE TITLE
network-manager-applet does not allow to disable wifi if connection to a wifi network is in progress

### ISSUE THREAD

**Issue by kenden** [linuxmint/network-manager-applet#1]
network-manager-applet does not allow to disable WIFI if connection to a wifi network is in progress.

When my laptop is docked, I prefer to disable the wifi to use only the Wired Network.
It is not possible to disable the wifi is the laptop is attempting to connect.
See screenshot: the on/off button is replaced by "Connecting"
Sometimes it attempts to connect for a long long time.

Workaround: open the network settings and turn wifi OFF from there.

$ cinnamon --version
Cinnamon 2.2.13

Apologises if this bug should go in:
https://bugs.launchpad.net/linuxmint
are there guidelines about where to enter bugs?

![menu_001](https://cloud.githubusercontent.com/assets/480586/3717859/615ee3c4-162d-11e4-8846-8d8b1040a641.png)

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/2eb6586ce7f49fae601f45fe9375fac44ad8c252
